import { PrismaClient } from '../../src/generated/prisma/client';

const prisma = new PrismaClient();

const SYSTEM_TEMPLATES = [
  {
    id: 'default-classic',
    name: 'Classic Grill',
    description: 'Traditional restaurant menu with tabs and grid layout',
    isSystem: true,
    config: {
      colors: {
        primaryColor: '#DC2626',
        secondaryColor: '#F5F5F5',
        backgroundColor: '#F5F5F5',
        surfaceColor: '#FFFFFF',
        textColor: '#0F172A',
        textSecondaryColor: '#64748B',
        borderColor: '#E5E7EB',
        successColor: '#22C55E',
        errorColor: '#DC2626',
        warningColor: '#F59E0B',
        accentColor: '#DC2626',
      },
      typography: {
        fontFamily: 'Poppins',
        headingFontFamily: 'Poppins',
        titleSize: 16,
        descriptionSize: 14,
        priceSize: 16,
        sectionTitleSize: 20,
        lineHeight: 1.4,
      },
      layout: {
        cardStyle: 'rounded',
        borderRadius: 12,
        cardSize: 'medium',
        cardSpacing: 12,
        imageAspectRatio: '1:1',
        maxImageHeight: 150,
      },
      menuStructure: {
        displayMode: 'tabs',
        sections: [],
      },
      productDisplay: {
        showImage: true,
        showName: true,
        showDescription: true,
        showPrice: true,
        pricePosition: 'below',
        showAddButton: true,
        addButtonStyle: 'icon',
        addButtonText: '+',
        showBadges: true,
        badgePosition: 'top-left',
        maxDescriptionLines: 2,
      },
      header: {
        showLogo: false,
        showRestaurantName: true,
        showAddress: true,
        showPhone: true,
        showDescription: true,
        showBusinessHours: true,
        headerStyle: 'full',
      },
      footer: {
        showFooter: true,
        customText: null,
        showPoweredBy: true,
      },
    },
  },
  {
    id: 'default-elegant',
    name: 'Elegant Café',
    description: 'Sophisticated café style with bordered cards and serif fonts',
    isSystem: true,
    config: {
      colors: {
        primaryColor: '#78350F',
        secondaryColor: '#FEF3C7',
        backgroundColor: '#FEF3C7',
        surfaceColor: '#FFFFFF',
        textColor: '#1C1917',
        textSecondaryColor: '#78716C',
        borderColor: '#D6D3D1',
        successColor: '#22C55E',
        errorColor: '#DC2626',
        warningColor: '#F59E0B',
        accentColor: '#78350F',
      },
      typography: {
        fontFamily: 'Georgia',
        headingFontFamily: 'Georgia',
        titleSize: 16,
        descriptionSize: 14,
        priceSize: 15,
        sectionTitleSize: 22,
        lineHeight: 1.5,
      },
      layout: {
        cardStyle: 'bordered',
        borderRadius: 4,
        cardSize: 'medium',
        cardSpacing: 16,
        imageAspectRatio: '4:3',
        maxImageHeight: 180,
      },
      menuStructure: {
        displayMode: 'scroll',
        sections: [],
      },
      productDisplay: {
        showImage: true,
        showName: true,
        showDescription: true,
        showPrice: true,
        pricePosition: 'below',
        showAddButton: true,
        addButtonStyle: 'text',
        addButtonText: 'Adicionar',
        showBadges: false,
        badgePosition: 'top-left',
        maxDescriptionLines: 3,
      },
      header: {
        showLogo: true,
        showRestaurantName: true,
        showAddress: true,
        showPhone: true,
        showDescription: true,
        showBusinessHours: false,
        headerStyle: 'minimal',
      },
      footer: {
        showFooter: true,
        customText: null,
        showPoweredBy: true,
      },
    },
  },
  {
    id: 'default-minimalist',
    name: 'Minimalist',
    description: 'Clean and simple text-only list layout',
    isSystem: true,
    config: {
      colors: {
        primaryColor: '#000000',
        secondaryColor: '#FFFFFF',
        backgroundColor: '#FFFFFF',
        surfaceColor: '#FFFFFF',
        textColor: '#000000',
        textSecondaryColor: '#6B7280',
        borderColor: '#E5E7EB',
        successColor: '#22C55E',
        errorColor: '#DC2626',
        warningColor: '#F59E0B',
        accentColor: '#000000',
      },
      typography: {
        fontFamily: 'Helvetica',
        headingFontFamily: 'Helvetica',
        titleSize: 15,
        descriptionSize: 0,
        priceSize: 15,
        sectionTitleSize: 18,
        lineHeight: 1.6,
      },
      layout: {
        cardStyle: 'square',
        borderRadius: 0,
        cardSize: 'small',
        cardSpacing: 0,
        imageAspectRatio: 'auto',
        maxImageHeight: 0,
      },
      menuStructure: {
        displayMode: 'list',
        sections: [],
      },
      productDisplay: {
        showImage: false,
        showName: true,
        showDescription: false,
        showPrice: true,
        pricePosition: 'below',
        showAddButton: false,
        addButtonStyle: 'icon',
        addButtonText: '+',
        showBadges: false,
        badgePosition: 'top-left',
        maxDescriptionLines: 0,
      },
      header: {
        showLogo: false,
        showRestaurantName: true,
        showAddress: false,
        showPhone: false,
        showDescription: false,
        showBusinessHours: false,
        headerStyle: 'minimal',
      },
      footer: {
        showFooter: false,
        customText: null,
        showPoweredBy: false,
      },
    },
  },
  {
    id: 'default-modern',
    name: 'Modern Fast Food',
    description: 'Vibrant fast food style with featured products and pill buttons',
    isSystem: true,
    config: {
      colors: {
        primaryColor: '#EA580C',
        secondaryColor: '#FFFFFF',
        backgroundColor: '#FFFFFF',
        surfaceColor: '#FFFFFF',
        textColor: '#1C1917',
        textSecondaryColor: '#78716C',
        borderColor: '#E5E7EB',
        successColor: '#22C55E',
        errorColor: '#DC2626',
        warningColor: '#F59E0B',
        accentColor: '#EA580C',
      },
      typography: {
        fontFamily: 'Inter',
        headingFontFamily: 'Inter',
        titleSize: 14,
        descriptionSize: 12,
        priceSize: 14,
        sectionTitleSize: 18,
        lineHeight: 1.3,
      },
      layout: {
        cardStyle: 'rounded',
        borderRadius: 20,
        cardSize: 'small',
        cardSpacing: 8,
        imageAspectRatio: '1:1',
        maxImageHeight: 100,
      },
      menuStructure: {
        displayMode: 'tabs',
        sections: [],
      },
      productDisplay: {
        showImage: true,
        showName: true,
        showDescription: false,
        showPrice: true,
        pricePosition: 'below',
        showAddButton: true,
        addButtonStyle: 'icon',
        addButtonText: '+',
        showBadges: true,
        badgePosition: 'overlay',
        maxDescriptionLines: 0,
      },
      header: {
        showLogo: false,
        showRestaurantName: true,
        showAddress: false,
        showPhone: false,
        showDescription: false,
        showBusinessHours: false,
        headerStyle: 'minimal',
      },
      footer: {
        showFooter: true,
        customText: null,
        showPoweredBy: false,
      },
    },
  },
  {
    id: 'default-vibrant',
    name: 'Vibrant & Fun',
    description: 'Colorful and playful with rounded cards and emoji icons',
    isSystem: true,
    config: {
      colors: {
        primaryColor: '#8B5CF6',
        secondaryColor: '#EC4899',
        backgroundColor: '#FDF4FF',
        surfaceColor: '#FFFFFF',
        textColor: '#1F2937',
        textSecondaryColor: '#6B7280',
        borderColor: '#E9D5FF',
        successColor: '#22C55E',
        errorColor: '#EF4444',
        warningColor: '#F59E0B',
        accentColor: '#8B5CF6',
      },
      typography: {
        fontFamily: 'Nunito',
        headingFontFamily: 'Nunito',
        titleSize: 16,
        descriptionSize: 13,
        priceSize: 15,
        sectionTitleSize: 20,
        lineHeight: 1.4,
      },
      layout: {
        cardStyle: 'rounded',
        borderRadius: 16,
        cardSize: 'medium',
        cardSpacing: 12,
        imageAspectRatio: '1:1',
        maxImageHeight: 140,
      },
      menuStructure: {
        displayMode: 'tabs',
        sections: [],
      },
      productDisplay: {
        showImage: true,
        showName: true,
        showDescription: true,
        showPrice: true,
        pricePosition: 'below',
        showAddButton: true,
        addButtonStyle: 'full',
        addButtonText: 'Adicionar',
        showBadges: true,
        badgePosition: 'top-right',
        maxDescriptionLines: 2,
      },
      header: {
        showLogo: false,
        showRestaurantName: true,
        showAddress: true,
        showPhone: true,
        showDescription: true,
        showBusinessHours: true,
        headerStyle: 'full',
      },
      footer: {
        showFooter: true,
        customText: null,
        showPoweredBy: true,
      },
    },
  },
];

async function seed() {
  console.log('Seeding system templates...');

  for (const template of SYSTEM_TEMPLATES) {
    await prisma.menuTemplate.upsert({
      where: { id: template.id },
      update: {
        name: template.name,
        description: template.description,
        config: template.config,
      },
      create: {
        id: template.id,
        name: template.name,
        description: template.description,
        isSystem: template.isSystem,
        isActive: false,
        config: template.config,
      },
    });
    console.log(`  ✓ ${template.name}`);
  }

  console.log('Seeding complete!');
}

seed()
  .catch((e) => {
    console.error('Error seeding:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
